sudo: required

language: generic

services:
  - docker

before_install:
  - echo "start creating ans image with dockerfile"
  - docker build -t csy.0414/docker-react-app -f Dockerfile.dev .

script:
  - docker run -e CI=true csy.0414/docker-react-app npm run test -- --coverage

deploy:
  provider: elasticbeanstalk
  region: "ap-northeast-2"
  app: "docker-react-app"
  env: "Dockerreactapp-env"
  bucket_name: "elasticbeanstalk-ap-northeast-2-229375602055"
  bucket_path: "elasticbeanstalk-ap-northeast-2-229375602055"
  on:
    branch: master
  access_key_id: $AWS_ACCESS_KEY
  secret_access_key: $AWS_SECRET_ACCESS_KEY