version: '3'
services:
  react:
    build:
      context: .
      dockerfile: Dockerfile.dev
    ports:
      - "3000:3000"
    working_dir: /usr/src/app
    volumes:
      - /usr/src/app/node_modules
      - D:\Docker_Project\docker-react-app:/usr/src/app
    stdin_open: true